/** Took most used lenguages to build app feature, if needed this could be scaled */
export const LANGUAGES = [
  { value: 'bn', label: 'বাংলা' },
  { value: 'de', label: 'Deutsch' },
  { value: 'el', label: 'Ελληνικά' },
  { value: 'en', label: 'English' },
  { value: 'he', label: 'עברית' },
  { value: 'hu', label: 'Magyar' },
  { value: 'ja', label: '日本語' },
  { value: 'la', label: '	Latina' },
  { value: 'sd', label: 'سنڌي، سندھی ، सिन्ध' },
  { value: 'sv', label: 'Svenska' },
  { value: 'ur', label: 'اردو' },
  { value: 'zh', label: '中文' },
  { value: 'bs', label: 'Bosanski' },
  { value: 'da', label: 'Dansk' },
  { value: 'es', label: 'Español' },
  { value: 'fi', label: 'Suomi' },
  { value: 'fr', label: 'Français' },
  { value: 'ko', label: '한국어' },
  { value: 'no', label: 'Norsk (Bokmål)' },
  { value: 'pl', label: 'Polski' },
  { value: 'pt', label: 'Português' },
  { value: 'ru', label: 'Русский' },
  { value: 'sco', label: 'Scots' },
  { value: 'vi', label: 'Tiếng Việt' },
  { value: 'ar', label: 'العربية' },
];
